ARG ENV_REPOSITORY=arcadiacoin/arcadia-env
FROM ${ENV_REPOSITORY}:base

RUN apt-get update -qq && apt-get install -yqq \
git \
libboost-all-dev

ARG REPOSITORY=arcadiacoin/arcadia-node
LABEL org.opencontainers.image.source https://github.com/$REPOSITORY
